### PR TITLE
added animation effect on contact, quick links, get involved links

### PR DESCRIPTION
**Pull request by rajat2203**

### CODE REVIEW

**Comment by xfurna** [comment]
Share the screenshots please.

**Comment by rajat2203** [comment]
IMG_20190727_215603

**Comment by rajat2203** [comment]
round box on hover with slightly black background

**Review by xfurna — CHANGES_REQUESTED** [review]
I appreciate the time that you've put for making these changes but honestly speaking, you've overdone it. We believe in minimalism and would rather like to stick to it.
I'm working on other projects on Bio1ixir which you can look into and try your hand at. Rest, feel free to discuss with me in person. 

**REQUESTED CHANGES:** Remove all borders, transitions, shadows and transformation and just change the hover color of `body .contact a:hover` to something brighter in pink shade.

**Comment by xfurna** [comment]
Will review it in a while. Thanks.

**Pull request closed without merging**
